version: '3'

networks:
    boardapi:
      driver: bridge

services:
    api:
      build:
        context: ./
        dockerfile: Dockerfile
      container_name: board-api
      depends_on:
        - postgres
      ports:
        - 8080:8080
      volumes:
        - ./:/board_fastapi
      networks:
        - boardapi
#      command: sh -c 'pipenv shell && uvicorn app.main:app --host 0.0.0.0 --port 8000'
#      command: sh -c 'uvicorn main:app --reload --host 0.0.0.0 --port 8000'
      command: sh -c 'python ./app/main.py'

    postgres:
      image: postgres:13
      environment:
          - POSTGRES_DB=developer
          - POSTGRES_USER=developer
          - POSTGRES_PASSWORD=devpassword
      volumes:
          - ./postgres-data:/var/lib/postgresql/data
      ports:
#        - "127.0.0.1:25000:5432"
        - 5432:5432
      networks:
        - boardapi

    redis:
      image: redis:latest
      ports:
#          - "127.0.0.1:25100:6379"
          - 6379:6379
      command: redis-server --save ""
      networks:
        - boardapi
#
#volumes:
#    postgres-data:
##        name: postgres-data
##        driver: local
#      external: true
